git:
  data:
    url: https://raw.githubusercontent.com/Thiedze/CWCocktailApi/master/data
    filldatabase: false
datasource:
  url: jdbc:mysql://sql343.your-server.de:3306/cocktail?serverTimezone=Europe/Berlin
  username: cocktail
  password:
  driver-class-name: com.mysql.cj.jdbc.Driver
  ddl-auto: create
logging:
  level:
    org:
      springframework.web: INFO
      hibernate: INFO
      hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR